nameOverride: echo

deployment:
  image:
    repository: kicbase/echo-server
    tag: "1.0"
  containerPort: 8080
  probes:
    initialDelaySeconds: 3
    livenessPath: /
    readinessPath: /
  replicaCount: 1

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: nginx
  hosts:
    - host: example.local # overwrite with helm cli
      paths:
        - path: /echo
          pathType: ImplementationSpecific
